// Auto-generated by scripts/fetch-bus-stops.js — do not edit manually
// Run the GitHub Actions workflow or: LTA_API_KEY=your_key node scripts/fetch-bus-stops.js
const BUS_STOPS = {};
export default BUS_STOPS;
